language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t archie-go/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true archie-go/docker-react npm run test