language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t archie-go/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true archie-go/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-832307970160"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY